### PR TITLE
don't crash on too long input lines

### PR DESCRIPTION
**Pull request by r00t-**

### CODE REVIEW

**Comment by armlabs** [comment]
actually this driver software would like to support many oled models at the same time. limiting buffer input to 20bytes may not be good to test oled if the display is more than 20 chars. so I will keep it unchanged.

**Comment by r00t-** [comment]
@armlabs:
a few lines above, your code defines `buf` to only store 20 characters:
https://github.com/armlabs/ssd1306_linux/blob/ff118b190cff211f31cf09da579b939e3ed67f25/ssd1306.c#L368
your code CRASHES (segmentation fault) if an input longer than 20 characters is given.
to support variable size displays, you would have to replace that fixed 20-char buffer with a dynamically allocated one.

**Comment by r00t-** [comment]
actually the fix is only partial, because the term `cr - line` in the other `strncpy()` might also exceed `20`.

**Comment by armlabs** [comment]
Yes you are right I mix up with top code of buffer with size 1024.
I will make a fix to solve this overflow issue.

**Comment by denisdemaisbr** [comment]
strncpy dont add null string sizeof-1 (worst  case)
use snprintf()

**Comment by armlabs** [comment]
> strncpy dont add null string sizeof-1 (worst case) use snprintf()

commit 19128ed4b6108408fea05b9d0551236b6d638dbc fixed this, thanks for your help.

**Pull request closed without merging**
